brace_style = "PreferSameLine"
wrap_comments = true
condense_wildcard_suffixes = true
edition = "2021"
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
format_generated_files = true
match_block_trailing_comma = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
max_width = 120
hex_literal_case = "Upper"
